name: CD
run-name: ${{ github.actor }} is running the CD ⚙️
on:
  # Runs this everytime a PR is merged against main
  push:
    branches:
      - main

# id-token: write is required so that GitHub Actions can request an OIDC token,
# which is then exchanged with GCP for a short-lived access token via WIF.
# contents: read allows the workflow to check out the repository code.
permissions:
  id-token: write   # REQUIRED for WIF
  contents: read

jobs:
    build-lint-test-deploy:
        runs-on: ubuntu-latest
        steps:
          # Fetches the GitHub repository files
          - name: Check out repository code 
            uses: actions/checkout@v4

          # Popular community-maintained action used to set up Flutter in GitHub workflows. 
          # Installs Flutter and allows you to run commands like flutter build, flutter test, and flutter analyze within your CI/CD pipeline.
          - name: Setup Flutter 
            uses: subosito/flutter-action@v2
            with:
              channel: 'stable'

          # Build app for web
          - name: Build flutter app for web 🛜
            run: flutter build web
          
          # Authenticates to GCP using Workload Identity Federation (WIF).
          # WIF allows GitHub Actions to obtain a short-lived access token by exchanging
          # its OIDC token with GCP — no long-lived service account keys are stored anywhere.
          - uses: google-github-actions/auth@v2
            with:
              workload_identity_provider: "projects/518851495309/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
              service_account: "cicd-workshop-sa@project-ef801521-090f-4fa8-9b5.iam.gserviceaccount.com"

          # Set the default GCP project for subsequent gcloud commands in your environment. 
          - name: Configure GCP Project
            run: gcloud config set project project-ef801521-090f-4fa8-9b

          # Configure Docker authentication for interacting with Artifact Registry, allowing you to push or pull Docker images securely.
          # Build the docker image and push it to artifact registry.
          # TODO: add your docker build and docker push commands here
          - name: Build and Push Docker Image 🐳
            run: |
              gcloud auth configure-docker --quiet
              gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

          # TODO: deploy your Docker image to Cloud Run
          - name: Deploy to Cloud Run ⚙️
            run: |
              echo "Deploy to Cloud Run"